language: java
jdk: openjdk7

env:
  global:
  - TERM=dumb

  # FTP credentials
  - secure: "FISpm2N1dpD9MRdU1gTIy3HegzG0JWNMult8bcZdWsIlyXGz+EhyLl2DQSiwUaeDNRg+MxuV7TeJAmXPe1VieY4JCJ7gT+ZnhSfuuWtEuq3XDvvrDuu0XCjRe4uKbWr4Wb3Vu9HgH8Im1zDyBtqU/pYcmcczysqpmnFL8x+7MS8="
  - secure: "Ycj3A/uWAAEmc1TOm8UNJkKMSohRzd2pDyjGnM7I+V3vn4GB7q2s4YtGJRJe559LlEXwwT3IJsuxHZGZRmmrJ2PukG8oAPaJQ/x8jxEMSSKVBS5IYdUlZ+67hyHdkrxBlGiVBmPkeJxNZrxpP18biAfF63u2QuyFO/YkVTl2UZc="
  - secure: "eTL8f2WIIl4vLmqODCBgVRjScGsQUzePESXuKaHuBXbZzPqsT85XtiFvdcqFZ53RaDd6I3fi8LzmYFH8/XBCCwfhPUGT2tEO12TBm1ScMhQ0nJ30xKZnSHW9RvEsowVjtFSrX9opAmopw3nbCFm/KUQdveB7deIMeB9bdjgO2YU="
  
branches:
  only:
  - master
  - develop

notifications:
  email: false
  irc: chat.freenode.net#syncany

before_install:
  # Standard Stuff
  - sudo apt-get update
  - sudo apt-get install -y -q lftp
  - lftp -v
  - mkdir ~/.gradle 2> /dev/null || true
  - echo "org.gradle.daemon=true" > ~/.gradle/gradle.properties

  # Debian Packaging
  - sudo apt-get install -y -q dh-make devscripts debhelper bash-completion
  - gpg --version
  - debuild --version
  - perl -v

install:
  # Disable default travis behavior 'gradle assemble'
  - ./gradlew -v

script:
  # Be safe and clean!
  - ./gradlew clean

  # Build JAR and Debian DEB
  - ./gradlew pluginJar
  - ./gradlew pluginDebianDeb  

  # Upload JARs and DEBs
  - core/gradle/lftp/lftpuploadplugin.sh
